name: Java CI
on: [push]
env:
  MAVEN_VERSION: 3.9.0
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: install java
        run: |
          sudo amazon-linux-extras enable corretto8
          sudo yum install java-11-amazon-corretto.x86_64 -y
          sudo yum list installed | grep java
          java -version
      - name: descargando maven
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
      - name: unzip maven
        run: |
          sudo tar xvf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt
      - name: create link maven
        run: |
          sudo ln -sf /opt/apache-maven-${MAVEN_VERSION} /opt/maven
      - name: create maven.sh
        run: |
          sudo touch /etc/profile.d/maven.sh && sudo chmod 777 /etc/profile.d/maven.sh && sudo cat>/etc/profile.d/maven.sh<< EOF export M2_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}
          EOF
      - name: privilegge maven.sh
        run: |
          sudo chmod 775 /etc/profile.d/maven.sh
          sudo chmod +x /etc/profile.d/maven.sh
      - name: reload profile maven.sh
        run: |
          source /etc/profile.d/maven.sh
      - name: version maven.sh
        run: |
          mvn -version
      - uses: actions/checkout@v3
      - name: check dir estructure
        run: |
          pwd
          ls -latR
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
          check-latest: true
      - name: Build with Maven glo
        #working-directory: '$HOME/actions-runner/_work/travels-java-api/travels-java-api/'
        run: mvn -B package --file pom.xml
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Create target dir
        run: mkdir staging && cp target/*.jar staging
      - name: check dir estructure
        run: |
          pwd
          ls -latR
      - name: Create artifac
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

